Import('*')

SimObject('UVEStreamingEngine.py')
Source('uve_ff_load.cc')
Source('uve_ff_store.cc')
Source('uve_se_controller_impl.cc')
Source('uve_se_mem_impl.cc')
Source('uve_streaming_engine.cc')

DebugFlag('UVESE')
